# frozen_string_literal: true

plugins:
  - rubocop-rails
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - "test/dummy/**/*"
    - "bin/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Style/Documentation:
  Enabled: false

# Disabled globally below

Style/FrozenStringLiteralComment:
  Enabled: true

# Disable metric cops that are too strict for this codebase
Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

# Disable predicate naming cop - allow has_* methods
Naming/PredicatePrefix:
  Enabled: false

# Disable multiple assertions cop for tests
Minitest/MultipleAssertions:
  Enabled: false

# Disable perceived complexity - similar to cyclomatic complexity
Metrics/PerceivedComplexity:
  Enabled: false

# Allow exit in CLI tools
Rails/Exit:
  Exclude:
    - "lib/rails_lens/cli_error_handler.rb"

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Layout/LineLength:
  Enabled: false

# Allow unused method arguments and variable names
Lint/UnusedMethodArgument:
  Enabled: false

# Allow duplicate branches for now
Lint/DuplicateBranch:
  Enabled: false

# Allow shadowed exceptions
Lint/ShadowedException:
  Enabled: false

# Allow method parameter names shorter than 3 chars (like 'fk')
Naming/MethodParameterName:
  Enabled: false

# Allow redundant else clauses
Style/EmptyElse:
  Enabled: false

# Allow safe navigation chains longer than 2
Style/SafeNavigationChainLength:
  Enabled: false

# Allow gem dependencies in gemspec
Gemspec/DevelopmentDependencies:
  Enabled: false

# Allow missing super in initialize
Lint/MissingSuper:
  Enabled: false

# Allow single line if/unless instead of modifier style
Style/IfUnlessModifier:
  Enabled: false

# Allow rescuing StandardError explicitly
Style/RescueStandardError:
  Enabled: false

Rails/Output:
  Enabled: false
